language: php
php:
    - 5.3
before_script:
    - cp app/config/parameters.ini.dist app/config/parameters.ini
    - php bin/vendors install
    - php app/console doctrine:database:create --env=test
    - php app/console doctrine:schema:create --env=test
