# security:
#     providers:
#         fos_userbundle:
#             id: fos_user.user_manager
#     encoders:
#         "FOS\UserBundle\Model\UserInterface": sha512

#     firewalls:
#         main:
#             pattern: .*
#             form_login:
#                 provider: fos_userbundle
#                 login_path: /login
#                 use_forward: false
#                 check_path: /login_check
#                 failure_path: null
#                 default_target_path: /
#             logout:
#                 path: /logout
#                 target: /
#             anonymous: true
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    firewalls:
        #Allow access to routes of profiler, web developper Toolbar and assets
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN